---
title: "Camping Weather notebook"
output: html_notebook
---

Notes and testing for the Camping Weather shiny app.

Doug Merrett ⓒ 2022 OFH Consulting

```{r}
## Install the required package with:
## install.packages("RSocrata")
## install.packages("remotes")
## install.packages("vetiver")

library("RSocrata")
library("dplyr")
library("lubridate")
library("timeDate")
library("vetiver")
library("leaflet")
library("DBI")
library("RSQLite")

setRmetricsOptions(myFinCenter = "Halifax")
today <- as.Date(Sys.timeDate())
```
### Load JSON data from the socrata API endpoint.
Search parameters in the load to pare the load down.  Pulling one stations complete data grabs over 100,000 records!
Should only need 4 days worth over however many years available
```{r}
# Read list of stations at start of session but not as inputs updated
# Get todays date for plot


# Create camping database of EC and lat/long station data to pull from

con <- dbConnect(RSQLite::SQLite(),"~/EnvCanDB.db")
curStation = "'KEJIMKUJIK 1'"
startMonth = "1"
startDay = "11"
qryStr <- paste("SELECT Station, DateTime_LST, Year, Month, Day, Temp_C from EC_temps WHERE Station LIKE ", curStation, " AND Month = ", startMonth, "AND Day = ", startDay, sep = " ")    
NS_Temps <- dbGetQuery(con,  qryStr)
dbDisconnect(con)
hist(NS_Temps$Temp_C)

#with(NSWXList, SiteID[Site_Name == "Avonport PW"])
#with(NSWXList, Lat[Site_Name == "Avonport PW"])
#with(NSWXList, Long[Site_Name == "Avonport PW"])

#stationList <- unique(stations$SiteID)

startTime <- Sys.time()
startDate <- today
endDate <- today + 4
#df <- read.socrata(
#  "https://data.novascotia.ca/resource/kafq-j9u4.json?$select=site_id,datetimeutc,air_temperature,date_extract_m(datetimeutc) as month,date_extract_d(datetimeutc) as #theday&$where=month = 10 AND (theday between 15 and 19) AND site_id='RNSAM'",
#  app_token = "YIJmci7v0Fd0eHtco6IXgFBuP"
#)
        qryStr = "https://data.novascotia.ca/resource/kafq-j9u4.json?$select=site_id,datetimeutc,air_temperature,date_extract_m(datetimeutc) as month,date_extract_d(datetimeutc) as theday&$where=month = 1 AND theday = 12 AND site_id= 'RNSAV'"
        df <- read.socrata(
          qryStr, app_token = "YIJmci7v0Fd0eHtco6IXgFBuP"
        )
df$theHour <- hour(df$datetimeutc)
df$theYear <- year(df$datetimeutc)
endTime <- Sys.time()
boxplot(as.numeric(air_temperature) ~ theHour, data = df, notch = TRUE)

# prints recorded time
# print(endTime - startTime)
```
### After the site load dig in to the data.

```{r}


```
